module.exports = {
  safe: true,
  sourcemaps: true,
  calc: {precision: 10},
  colormin: true,
  convertValues: false,
  discardComments: false,
  discardDuplicates: true,
  discardEmpty: true,
  discardUnused: false,
  filterPlugins: {direction: 'backward'},
  mergeIdents: true,
  mergeLonghand: false,
  mergeRules: true,
  minifyFontValues: false,
  minifySelectors: true,
  normalizeCharset: true,
  normalizeUrl: false,
  orderedValues: true,
  reduceIdents: false,
  reduceTransforms: false,
  svgo: true,
  uniqueSelectors: true,
  zindex: false
}
